<?php

namespace slkj\unionpay\test;

use PHPUnit\Framework\TestCase;

/**
 * Class BaseTestCase
 * @package slkj\unionpay
 */
class BaseTestCase extends TestCase
{
    const CRLF = "\r\n";

    public static function autoload($class_name) {
        require_once ($class_name . ".php");
    }

    public function testIsTestCase() {
        $message = 'Test-Case';
        $this->assertTrue(strtolower($message) === 'test-case');
    }

    protected function setUp(): void {
        parent::setUp();

        echo self::CRLF . "TestCase: SetUp..." . self::CRLF;

        include_once(__DIR__ . '/../../../bootstrap.php');
        $path = realpath(__DIR__ . '/../../main/php/');
        echo "The source codes path of unionpay-php project is: $path";
        set_include_path($path);
        spl_autoload_register("\\slkj\\unionpay\\test\\BaseTestCase::autoload");
    }

    protected function tearDown(): void {
        parent::tearDown(); // TODO: Change the autogenerated stub

        echo self::CRLF . "TestCase: TearDown." . self::CRLF;
    }

}